spring:
  application:
    name: spring-cloud-system
server:
  port: 9092
eureka:
  hostname: service-system
  prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-eureka:9090/eureka/