discovery:
  image: cjy/service-eureka
  container_name: eureka
  hostname: service-eureka
  ports:
    - "9090:9090"

producer:
  image:  cjy/service-producer
  container_name: producer
  ports:
    - "9093:9093"
  links:
    - "discovery"

system:
  image:  cjy/service-system
  container_name: system
  ports:
    - "9092:9092"
  links:
    - "discovery"

feign:
  image:  cjy/service-feign
  container_name: feign
  ports:
    - "9094:9094"
  links:
    - "discovery"
    - "producer"

ribbon:
  image:  cjy/service-ribbon
  container_name: ribbon
  ports:
    - "9091:9091"
  links:
    - "discovery"
    - "system"