spring:
  application:
    name: spring-cloud-producer
server:
  port: 9093
eureka:
  instance:
    hostname: service-producer
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-eureka:9090/eureka/