server:
  port: 9095
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/passionchenjianye/config-repo/     # 配置git仓库的地址
          search-paths: configs                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: passionchenjianye@gmail # git仓库的账号
          password: CJY@3296406apple
eureka:
  instance:
    hostname: config-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-eureka:9090/eureka/