spring:
  application:
    name: spring-cloud-api-gateway
server:
  port: 9096
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
zuul:
  routes:
    comsumer:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /api/**                                   # 想要映射到的路径
      service-id: spring-cloud-comsumer            # Eureka中的serviceId